update_image:
  tags: [ docker_itsoft ]
  image: docker:20.10.21
  services: [ docker:20.10.21-dind ]

  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh -p 22 "${USER}"@"${HOST}" "docker-compose -f superset/docker-compose-non-dev.yml pull && docker-compose -f superset/docker-compose-non-dev.yml up -d"

  when: manual
